### ISSUE TITLE
`Distributions.jl` in compat section

### ISSUE THREAD

**Issue by kir19890817** [davidavdav/GaussianMixtures.jl#94]
I've recently bumped into a problem trying to install `GaussinMixtures.jl` together with a few other packages, because of strict `compat` section in `Project.toml`, in particular the constrains related to `Distributions.jl`. In my project `GaussianMixtures.jl` successfully coexists with `Distributions.jl@v0.25.16`. I suggest easing this constraint.

**Comment by ForceBru** [comment]
Same thing with `PDMats`: the latest version is v0.11.1, but installing GaussianMixtures.jl downgrades it to v0.11.1.

As a side note, I find it odd that installing one package can easily downgrade my installed packages without warning, sometimes several major versions down, such that they no longer provide the features my code uses, so _my code_ breaks because I installed some other package.

**Comment by davidavdav** [comment]
Hi, yes this is a place in dependency hell that I haven't visited a lot.  I think there is a whole Julia / github infrastructure for getting notified when there are new versions of dependencies, but I think it explicitly doesn't do testing, so I've turned all these things off as it appears useless to me. 

I am happy to update these compatibility restrictions to something that has been tested to work. 

Specifically for `Distributions.jl` the dependency isn't very strict, I think that this package only has an export function for Distributions, it doesn't functionally depend on it.

**Comment by yuehhua** [comment]
I have this package as dependency for my own package. I found it is blocked by Distributions.jl version rooted in this package. I hope these compats can be picked up and get package maintained well.
